col type for a5
col ts for a5

spool add_indexes_LICENSE_NUMBER.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on



set echo on timing on head off


CREATE INDEX PROD.FK_LICENSE_NUMBER_CODE_ENTRY
    ON PROD.LICENSE_NUMBER(CD_ENTRY_ID)
TABLESPACE INDX3 ONLINE PARALLEL 6;

CREATE INDEX PROD.FK_LI_NBR_CD_RY_LICENSE_E_RSN
    ON PROD.LICENSE_NUMBER(LICENSE_TE_NATE_RSN_CD_TRY_ID)
TABLESPACE INDX3 ONLINE PARALLEL 6;


CREATE INDEX PROD.LICENSE_NUMBER_IDX
    ON PROD.LICENSE_NUMBER(LICENSE_NBR)
TABLESPACE INDX3 ONLINE PARALLEL 6;







alter session set DDL_LOCK_TIMEOUT = 300;

ALTER INDEX PROD.FK_LICENSE_NUMBER_CODE_ENTRY NOPARALLEL;
ALTER INDEX PROD.FK_LI_NBR_CD_RY_LICENSE_E_RSN NOPARALLEL;
ALTER INDEX PROD.LICENSE_NUMBER_IDX NOPARALLEL;

set echo off timing off head on feed on


set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off
