col type for a5
col ts for a5

spool add_indexes_HCFA1500.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on



set echo on timing on head off



CREATE INDEX PROD.FK_HCFA1500_SUPERVISING_PRACT
    ON PROD.HCFA1500(SUPERVISING_PRACT_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.FK_HC_500_SPPLR_INV_MENTED_NM
    ON PROD.HCFA1500(SPPLR_INV_SEGMENTED_NM_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.FK_H_00_SPPLR_I_TED_NM_SEGM_NM
    ON PROD.HCFA1500(SEGME_NM_SPPLR_IN_NTED_NM_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.TENANTID_HCFA1500
    ON PROD.HCFA1500(TENANT_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;






alter session set DDL_LOCK_TIMEOUT = 300;

ALTER INDEX PROD.FK_HCFA1500_SUPERVISING_PRACT NOPARALLEL;
ALTER INDEX PROD.FK_HC_500_SPPLR_INV_MENTED_NM NOPARALLEL;
ALTER INDEX PROD.FK_H_00_SPPLR_I_TED_NM_SEGM_NM NOPARALLEL;
ALTER INDEX PROD.FK_H_00_SPPLR_I_TED_NM_SEGM_NM NOPARALLEL;

set echo off timing off head on feed on


set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off
