col type for a5
col ts for a5

spool add_indexes_UB92.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on



set echo on timing on head off



CREATE INDEX PROD.FK_UB92_SPPLR_INV_SEGMENTED_NM
    ON PROD.UB92(SPPLR_INV_SEGMENTED_NM_ID)
TABLESPACE INDX3 ONLINE PARALLEL 6;


CREATE INDEX PROD.FK_UB92_UB92_DIAGNOSIS
    ON PROD.UB92(UB92_DIAG_ID)
TABLESPACE INDX3 ONLINE PARALLEL 6;


CREATE INDEX PROD.FK_UB92_UB_PRACTITIONER
    ON PROD.UB92(UB_PRACT_ID)
TABLESPACE INDX3 ONLINE PARALLEL 6;


CREATE INDEX PROD.FK_U_2_UB_P_CT_OPERATIN_PRACT
    ON PROD.UB92(OPERATING_PRACT_UB_PRACT_ID)
TABLESPACE INDX3 ONLINE PARALLEL 6;


CREATE INDEX PROD.TENANTID_UB92
    ON PROD.UB92(TENANT_ID)
TABLESPACE INDX3 ONLINE PARALLEL 6;



alter session set DDL_LOCK_TIMEOUT = 300;

ALTER INDEX PROD.FK_UB92_SPPLR_INV_SEGMENTED_NM NOPARALLEL;
ALTER INDEX PROD.FK_UB92_UB92_DIAGNOSIS NOPARALLEL;
ALTER INDEX PROD.FK_UB92_UB_PRACTITIONER NOPARALLEL;
ALTER INDEX PROD.FK_U_2_UB_P_CT_OPERATIN_PRACT NOPARALLEL;
ALTER INDEX PROD.TENANTID_UB92 NOPARALLEL;

set echo off timing off head on feed on


set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off
