col type for a5
col ts for a5

spool add_indexes_POSTAL_ADDRESS.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on



set echo on timing on head off



CREATE INDEX PROD.ADDR_TXT_UP_IDX
    ON PROD.POSTAL_ADDRESS(UPPER("ADDR_TXT"))
TABLESPACE INDX5 ONLINE PARALLEL 6;

CREATE INDEX PROD.ADDR_ZIP_UP_IDX
    ON PROD.POSTAL_ADDRESS(UPPER("ADDR_TXT"),UPPER("ZIP_CD"))
TABLESPACE INDX5 ONLINE PARALLEL 6;

CREATE INDEX PROD.CITY_NM_UP_IDX
    ON PROD.POSTAL_ADDRESS(UPPER("CITY_NM"))
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.POSTAL_ADDRESS_AEDBA_1
    ON PROD.POSTAL_ADDRESS(UPPER("ZIP_CD"),UPPER("CITY_NM"),UPPER("STATE_CD"),VER_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.POSTAL_ADDRESS_AEDBA_2
    ON PROD.POSTAL_ADDRESS(UPPER("CITY_NM"),UPPER("ZIP_CD"),UPPER("STATE_CD"),VER_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;



CREATE INDEX PROD.POSTAL_ADDRESS_ID
    ON PROD.POSTAL_ADDRESS(POSTAL_ADDR_ID,VER_ID,UPPER("ADDR_TXT"),UPPER("ZIP_CD"),UPPER("CITY_NM"))
TABLESPACE INDX4 ONLINE PARALLEL 6;

CREATE INDEX PROD.POSTAL_ADDR_GEO
    ON PROD.POSTAL_ADDRESS(LATITUDE,LONGITUDE,POSTAL_ADDR_ID,VER_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;

CREATE INDEX PROD.POSTAL_INDX
    ON PROD.POSTAL_ADDRESS(UPPER("ZIP_CD"),POSTAL_ADDR_ID,VER_ID)
TABLESPACE INDX5 ONLINE PARALLEL 6;

CREATE INDEX PROD.STATE_CD_UP_IDX
    ON PROD.POSTAL_ADDRESS(UPPER("STATE_CD"))
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.VER_ID_ADDR_ZIP_AEDBA_1
    ON PROD.POSTAL_ADDRESS(VER_ID,POSTAL_ADDR_ID,UPPER("ADDR_TXT"),UPPER("ZIP_CD"))
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.ZIP_CD_UP_IDX
    ON PROD.POSTAL_ADDRESS(UPPER("ZIP_CD"))
TABLESPACE INDX5 ONLINE PARALLEL 6;


CREATE INDEX PROD.FK_POS_RANGE_INTERNATI_V_AREA
    ON PROD.POSTAL_CODE_RANGE(QXJ__PARENT)
TABLESPACE INDX5 ONLINE PARALLEL 6;


alter session set DDL_LOCK_TIMEOUT = 300;

ALTER INDEX PROD.ADDR_TXT_UP_IDX NOPARALLEL;
ALTER INDEX PROD.ZIP_CD_UP_IDX NOPARALLEL;
ALTER INDEX PROD.VER_ID_ADDR_ZIP_AEDBA_1 NOPARALLEL;
ALTER INDEX PROD.STATE_CD_UP_IDX NOPARALLEL;
ALTER INDEX PROD.POSTAL_INDX NOPARALLEL;
ALTER INDEX PROD.POSTAL_ADDRESS_ID NOPARALLEL;
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_2 NOPARALLEL;
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_1 NOPARALLEL;
ALTER INDEX PROD.CITY_NM_UP_IDX NOPARALLEL;
ALTER INDEX PROD.ADDR_ZIP_UP_IDX NOPARALLEL;
ALTER INDEX PROD.POSTAL_ADDR_GEO NOPARALLEL;
ALTER INDEX PROD.FK_POS_RANGE_INTERNATI_V_AREA NOPARALLEL;



set echo off timing off head on feed on


set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off
