col type for a5
col ts for a5

spool add_indexes_PAYEE_BANK_ACCOUNTS.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on



set echo on timing on head off


CREATE INDEX PROD.ALIAS_PAYEE_BANK_ACCOUNTS
    ON PROD.PAYEE_BANK_ACCOUNTS(UPPER("BANK_ACCT_ID_1"),
CONCEPT_FULFILLED_CD,
VER_EFF_DT,
VER_EXPIRE_DT,
ENDOR_EFF_DT,
ENDOR_EXPIRE_DT
)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
ONLINE PARALLEL 6
NOCOMPRESS
/


CREATE INDEX PROD.FK_PAYEE_ACCOUNTS_BUSIN_SEG
    ON PROD.PAYEE_BANK_ACCOUNTS(BUSINESS_SEG_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/


CREATE INDEX PROD.FK_PAYEE_ACCOUNTS_EXTER_MBR
    ON PROD.PAYEE_BANK_ACCOUNTS(EXTERNAL_MBR_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_ACCOUNT
    ON PROD.PAYEE_BANK_ACCOUNTS(ACCT_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_BROKER
    ON PROD.PAYEE_BANK_ACCOUNTS(BROKER_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_MBRSHP
    ON PROD.PAYEE_BANK_ACCOUNTS(MBRSHP_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_SPPLR
    ON PROD.PAYEE_BANK_ACCOUNTS(SPPLR_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_SUBSCRP
    ON PROD.PAYEE_BANK_ACCOUNTS(SUBSCRP_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/


CREATE INDEX PROD.FK_PAYEE_B_ACCOUNTS_AUDIT_OG
    ON PROD.PAYEE_BANK_ACCOUNTS(AUDIT_LOG_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.FK_PAYEE_B_ACCOUNTS_LIEN_LDER
    ON PROD.PAYEE_BANK_ACCOUNTS(LIEN_HOLDER_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.FK_PAYEE_B_ACCOUNTS_SPPLR_OC
    ON PROD.PAYEE_BANK_ACCOUNTS(SPPLR_LOC_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.PAYEE_BANK_ACCOUNTS_AEDBA_1
    ON PROD.PAYEE_BANK_ACCOUNTS(INST_ACTIVE_CD,SPPLR_ID,SPPLR_LOC_ID,TENANT_ID,BANK_ACCT_ID,VER_ID)
TABLESPACE INDX4
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
ONLINE PARALLEL 6
NOCOMPRESS
/


CREATE INDEX PROD.TENANTID_PAYEE_BANK_ACCOUNTS
    ON PROD.PAYEE_BANK_ACCOUNTS(TENANT_ID)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
REVERSE
ONLINE PARALLEL 6
NOCOMPRESS
/

CREATE INDEX PROD.VIDDATES_PAYEE_BANK_ACCOUNTS
    ON PROD.PAYEE_BANK_ACCOUNTS(VER_ID,CONCEPT_FULFILLED_CD,VER_EFF_DT,VER_EXPIRE_DT,ENDOR_EFF_DT,ENDOR_EXPIRE_DT)
TABLESPACE INDX5
LOGGING
PCTFREE 10
INITRANS 2
MAXTRANS 255
STORAGE(INITIAL 64K
        BUFFER_POOL DEFAULT)
ONLINE PARALLEL 6
NOCOMPRESS
/







ALTER INDEX PROD.ALIAS_PAYEE_BANK_ACCOUNTS NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_ACCOUNTS_BUSIN_SEG NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_ACCOUNTS_EXTER_MBR NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_ACCOUNT NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_BROKER NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_MBRSHP NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_SPPLR NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_SUBSCRP NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_B_ACCOUNTS_AUDIT_OG NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_B_ACCOUNTS_LIEN_LDER NOPARALLEL;
ALTER INDEX PROD.FK_PAYEE_B_ACCOUNTS_SPPLR_OC NOPARALLEL;
ALTER INDEX PROD.PAYEE_BANK_ACCOUNTS_AEDBA_1 NOPARALLEL;
ALTER INDEX PROD.TENANTID_PAYEE_BANK_ACCOUNTS NOPARALLEL;
ALTER INDEX PROD.VIDDATES_PAYEE_BANK_ACCOUNTS NOPARALLEL;




set echo off timing off head on feed on


set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off

