- name: Create recovery catalog
  when:
    - ansible_domain is search("aetna")
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.command: "{{ oracle_base }}/local/scripts/create_rcat.sh {{ db_name }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_{{ db_name }}_successful"

- name: Setup rman config commands
  become: true
  ansible.builtin.template:
    src: configure.rman.j2
    dest: "{{ oracle_base }}/admin/{{ db_name }}/rman/configure.rman"
    owner: oracle
    group: dba
    mode: "0755"

- name: Configure RMAN
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.command: >-
    {{ oracle_home }}/bin/rman target / cmdfile={{ oracle_base }}/admin/{{ db_name }}/rman/configure.rman
    log={{ oracle_base }}/admin/{{ db_name }}/rman/configure_{{ db_name }}.log
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
    LD_LIBRARY_PATH: "{{ oracle_home }}/lib"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_{{ db_name }}_successful"