spool create_aedba_string_users.out
set echo on
CREATE TABLE "AEDBA"."STRONG_USERS" ( "USERNAME" VARCHAR2(10), "EMAIL_ADDRESS" VARCHAR2(50), "LAST_NAME" VARCHAR2(50), "FIRST_NAME" VARCHAR2(50), CONSTRAINT "USERNAME_PK" PRIMARY KEY ("USERNAME") VALIDATE ) TABLESPACE "AUDIT_SPACE" PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K BUFFER_POOL DEFAULT) LOGGING NOCOMPRESS;

CREATE UNIQUE INDEX "AEDBA"."USERNAME_PK" ON "AEDBA"."STRONG_USERS" ("USERNAME") TABLESPACE "AUDIT_SPACE" PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE ( INITIAL 64K BUFFER_POOL DEFAULT) LOGGING NOCOMPRESS;
spool off
