
Rem ----- V ----- cut ----- V ----- cut ----- V ----- cut ----- V ----- cut ----- V
set termout off
column timecol new_value timestamp
column spool_extension new_value suffix
SELECT to_char(sysdate,'dd-Mon-yyyy_hh24miss') timecol,'.outt' spool_extension FROM sys.dual;
column output new_value dbname
SELECT value || '_' output FROM v$parameter WHERE name = 'db_name';
set termout on
spool /orahome/u01/app/oracle/local/logs/create_s058102___&&dbname&&timestamp&&suffix
set echo on
Rem ----- ^ ----- cut ----- ^ ----- cut ----- ^ ----- cut ----- ^ ----- cut ----- ^

WHENEVER SQLERROR EXIT SQL.SQLCODE;
CREATE USER S058102
  IDENTIFIED BY  "o#5W5NXNo#5W5NXN"
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE TRUSTED_ID_NO_EXPIRE
  ACCOUNT UNLOCK;

  -- 4 Roles for S058102
  GRANT CREATE TABLE TO S058102;
  GRANT CREATE SESSION TO S058102;
  GRANT SELECT_CATALOG_ROLE TO S058102;
  GRANT SELECT ANY DICTIONARY TO S058102;
  GRANT UNLIMITED TABLESPACE TO S058102;
  GRANT SELECT ANY TABLE TO S058102;

   -- 19 Object Privileges for S058102
    GRANT SELECT ON SYS.DBA_DATA_FILES TO S058102;
    GRANT SELECT ON SYS.DBA_DIRECTORIES TO S058102;
    GRANT SELECT ON SYS.DBA_EXTENTS TO S058102;
    GRANT SELECT ON SYS.DBA_FREE_SPACE TO S058102;
    GRANT SELECT ON SYS.DBA_HIST_SNAPSHOT TO S058102;
    GRANT SELECT ON SYS.DBA_HIST_SQLSTAT TO S058102;
    GRANT SELECT ON SYS.DBA_OBJECTS TO S058102 WITH GRANT OPTION;
    GRANT SELECT ON SYS.DBA_ROLE_PRIVS TO S058102 WITH GRANT OPTION;
    GRANT SELECT ON SYS.DBA_TABLESPACES TO S058102;
    GRANT SELECT ON SYS.DBA_TEMP_FILES TO S058102;
    GRANT SELECT ON SYS.DEPENDENCY$ TO S058102 WITH GRANT OPTION;
    GRANT SELECT ON SYS.DUAL TO S058102;
    GRANT SELECT ON SYS.PUBLIC_DEPENDENCY TO S058102 WITH GRANT OPTION;
    GRANT SELECT ON SYS.REGISTRY$HISTORY TO S058102;
    GRANT SELECT ON SYS.USER$ TO S058102;
    GRANT SELECT ON SYS.V_$DATABASE TO S058102;
    GRANT SELECT ON SYS.V_$INSTANCE TO S058102;
    GRANT SELECT ON SYS.V_$NLS_PARAMETERS TO S058102;
    GRANT SELECT ON SYS.V_$SESSION TO S058102;

spool off
