spool create_tablespaces.out
set echo on
CREATE BIGFILE TABLESPACE "DATA" DATAFILE '+DATA_01' SIZE 1G LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
CREATE BIGFILE TABLESPACE "INDEX" DATAFILE '+DATA_01' SIZE 1G LOGGING EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO;
spool off
