CREATE PROFILE "TRUSTED_ID_NO_EXPIRE" LIMIT CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME DEFAULT
SESSIONS_PER_USER DEFAULT
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
PASSWORD_REUSE_MAX 6
PASSWORD_REUSE_TIME 365
PASSWORD_LOCK_TIME 1
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_VERIFY_FUNCTION AI_PASSWORD_VALIDATE_V2;

