
CREATE PROFILE "C##STANDARD" LIMIT CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
CONNECT_TIME DEFAULT
IDLE_TIME DEFAULT
SESSIONS_PER_USER DEFAULT
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
PRIVATE_SGA DEFAULT
COMPOSITE_LIMIT DEFAULT
PASSWORD_LIFE_TIME 80
PASSWORD_GRACE_TIME 10
PASSWORD_REUSE_MAX 24
PASSWORD_REUSE_TIME 390
PASSWORD_LOCK_TIME .0034
FAILED_LOGIN_ATTEMPTS 5
PASSWORD_VERIFY_FUNCTION AI_PASSWORD_VALIDATE_V2
