
CREATE TABLE "AEDBA"."STRONG_LOG" ( "ID" NUMBER(6), "USERNAME" VARCHAR2(30), "VALUE" VARCHAR2(80)) TABLESPACE "AUDIT_SPACE" PCTFREE 10 INITRANS 1 MAXTRANS 255 STORAGE ( INITIAL 64K BUFFER_POOL DEFAULT) LOGGING NOCOMPRESS
