ALTER DATABASE STOP LOGICAL STANDBY APPLY;
EXECUTE DBMS_LOGSTDBY.SKIP('SCHEMA_DDL','MYPIHMS', '%', NULL, TRUE, '\');
EXECUTE DBMS_LOGSTDBY.SKIP('DML','MYPIHMS', '%', NULL, TRUE, '\');
EXECUTE DBMS_LOGSTDBY.SKIP_ERROR('GRANT') 

-- Skip the non-logged work done by the compression advisor
EXECUTE DBMS_LOGSTDBY.SKIP('SCHEMA_DDL','PHIMS_EXPIMP', '%', NULL, TRUE, '\');
EXECUTE DBMS_LOGSTDBY.SKIP('DML','PHIMS_EXPIMP', '%', NULL, TRUE, '\');
exec DBMS_LOGSTDBY.SKIP (stmt =>'DML', schema_name=>'%', object_name =>'DBMS_TABCOMP%', use_like=>TRUE)
exec DBMS_LOGSTDBY.SKIP (stmt =>'TABLE', schema_name=>'%', object_name =>'DBMS_TABCOMP%', use_like=>TRUE)
ALTER DATABASE GUARD NONE;

