DROP INDEX PROD.PRSN_NAME_IDX
/
DROP INDEX PROD.PERS_NM_PRFX_CD_NORM
/
DROP INDEX PROD.PERS_NM_MID_NM_NORM
/
DROP INDEX PROD.PERS_NM_LAST_NM_UP
/
DROP INDEX PROD.PERS_NM_LAST_NM_NORM
/
DROP INDEX PROD.PERS_NM_LAST_1ST_CASE
/
DROP INDEX PROD.PERS_NM_LAST_1ST
/
DROP INDEX PROD.PERS_NM_1ST_NM_UP
/
DROP INDEX PROD.PERS_NM_1ST_NM_NORM
/