DROP INDEX PROD.FK_CAPITATED_PAYMENT_LINE_ZIP

/
DROP INDEX PROD.FK_CAPITATED_PAYMNT_LN_COUNTY
/

DROP INDEX PROD.FK_CAPITATED_PAYMNT_LN_MBRSHP
/
DROP INDEX PROD.FK_CAPITATED_PAYMNT_LN_SUBSCRP
/
DROP INDEX PROD.FK_CAPITATE_PAYMNT_LN_CD_E_RY
/
DROP INDEX PROD.FK_CAPITATE_PAYMNT_LN_COV_IER
/
DROP INDEX PROD.FK_CAPITAT_AYMNT_LN_MBR_P_MB
/
DROP INDEX PROD.FK_CAPITAT_AYMNT_LN_ZI_MBR_IP
/
DROP INDEX PROD.FK_CAPITAT_PAYMNT_LN_BNFT_LAN
/
DROP INDEX PROD.FK_CAPITAT_PAYMNT_LN_SPPLR_OC
/
DROP INDEX PROD.FK_CAPITA_AYMNT_LN_COV_T_SET
/
DROP INDEX PROD.FK_CAPITA_AYMNT_LN_SPPLR_TWRK
/
DROP INDEX PROD.FK_CAPIT_MNT_LN_CD_RY_PANE_PE
/
DROP INDEX PROD.FK_CAPIT_MNT_LN_CD_RY_ROST_PE
/
DROP INDEX PROD.FK_CAPIT_MNT_LN_CO_Y_PRVD_NTY
/
DROP INDEX PROD.FK_CAPIT_YMNT_LN_CD_RY_SPEC_V
/
DROP INDEX PROD.FK_CAPIT_YMNT_LN_CO_Y_MBR_NTY
/
DROP INDEX PROD.FK_CAPI_MNT_LN_CD_RY_MBR_H_ND
/
DROP INDEX PROD.FK_CAPI_MNT_LN_SPPL_RK_SPEC_RK
/
DROP INDEX PROD.FK_CAP_NT_LN_CAPITATE_DETAIL
/
DROP INDEX PROD.TENANTID_CAPITATED_PAYMNT_LN
/