

DROP INDEX PROD.CC_AEDBA_3
/

DROP INDEX PROD.CC_AEDBA_4
/

DROP INDEX PROD.CC_CLEAR_TRACE_NBR
/

DROP INDEX PROD.CC_EXT_BATCH_NBR
/

DROP INDEX PROD.CC_EXT_CLAIM_NUMBER
/

DROP INDEX PROD.CC_EXT_EF_CLAIM_NBR
/

DROP INDEX PROD.CC_HCC_CLM_NBR
/

DROP INDEX PROD.CC_HCC_CLM_NBR_UP
/

DROP INDEX PROD.CC_RECEIPT_DATE
/
DROP INDEX PROD.CC_STATE_ENDOR_DT
/

DROP INDEX PROD.CC_UNRESOLVED_REPROCESS
/

DROP INDEX PROD.FK_CONSLTD_CLM_ATTACHMENT_SET
/

DROP INDEX PROD.FK_CONSLTD_CLM_AUDIT_LOG
/

DROP INDEX PROD.FK_CONSLTD_CLM_CD_ENTRY
/

DROP INDEX PROD.FK_CONSLTD_CLM_CLM_BATCH
/

DROP INDEX PROD.FK_CONSLTD_CLM_CLM_TOTAL
/

DROP INDEX PROD.FK_CONSLTD_CLM_CONSLTD_CLM
/

DROP INDEX PROD.FK_CONSLTD_CLM_DENT_CLM_INFO
/

DROP INDEX PROD.FK_CONSLTD_CLM_DIAG
/

DROP INDEX PROD.FK_CONSLTD_CLM_DIAG_INFO
/

DROP INDEX PROD.FK_CONSLTD_CLM_DISCHRG_STATUS
/

DROP INDEX PROD.FK_CONSLTD_CLM_EXTERNAL_MBR
/

DROP INDEX PROD.FK_CONSLTD_CLM_GEN_VER_REF
/

DROP INDEX PROD.FK_CONSLTD_CLM_MBRSHP
/

DROP INDEX PROD.FK_CONSLTD_CLM_PERSON_NM
/

DROP INDEX PROD.FK_CONSLTD_CLM_PHONE
/

DROP INDEX PROD.FK_CONSLTD_CLM_PLACE_OF_SERV
/

DROP INDEX PROD.FK_CONSLTD_CLM_POSTAL_ADDR
/

DROP INDEX PROD.FK_CONSLTD_CLM_PRACT
/

DROP INDEX PROD.FK_CONSLTD_CLM_PROC_INFO
/

DROP INDEX PROD.FK_CONSLTD_CLM_PRVDR_TAXONOMY
/

DROP INDEX PROD.FK_CONSLTD_CLM_SPPLR_INV
/

DROP INDEX PROD.FK_CONSLTD_CLM_SPPLR_LOC
/

DROP INDEX PROD.FK_CONSLTD_CLM_SUBSCRP
/

DROP INDEX PROD.FK_CONSLTD_CLM_TYPE_OF_BILL
/

DROP INDEX PROD.FK_CONSOLIDATED_CLAIM_DRG
/

DROP INDEX PROD.FK_CONSOLIDATED_CLAIM_SUPPLIER
/

DROP INDEX PROD.FK_CONS_D_CLM_CD_E_RY_ADMS_RC
/

DROP INDEX PROD.FK_CONS_D_CLM_CD_E_RY_CLM_RC
/

DROP INDEX PROD.FK_CONS_D_CLM_DR_DRG_OV_RIDE
/

DROP INDEX PROD.FK_CONS_D_CLM_POSTAL_DDR_AD
/

DROP INDEX PROD.FK_CONS_D_CLM_PRA_ATTND_RACT
/

DROP INDEX PROD.FK_CON_CLM_CD_TRY_ADMS_E_CD
/

DROP INDEX PROD.FK_CON_CLM_CD_TRY_BNFT_P_TYPE
/

DROP INDEX PROD.FK_CON_CLM_CD_TRY_DATE_L_CD
/

DROP INDEX PROD.FK_CON_CLM_DR_CALCULAT_RG_CD
/

DROP INDEX PROD.FK_CON_CLM_POSTA_DR_PAY_T_DR
/

DROP INDEX PROD.FK_CON_CLM_PRA_OPERATI_RACT
/

DROP INDEX PROD.FK_CON_CLM_SPPLR_INV_NTED_NM
/

DROP INDEX PROD.FK_CON_CLM_SPPL_NV_CURREN_PUT
/

DROP INDEX PROD.FK_CON_D_CLM_CLM_TOTA_OR_PLAN
/

DROP INDEX PROD.FK_CO_CLM_BLUE_CARD_ADER_INFO
/

DROP INDEX PROD.FK_CO_CLM_BLUE_CARD_NG_RESULT
/

DROP INDEX PROD.FK_CO_CLM_CLM_DELEG_TRIBUTES
/

DROP INDEX PROD.FK_CO_CLM_CONS_LM_PREVIO_TATE
/

DROP INDEX PROD.FK_CO_CLM_POST_DR_RESPBL_ADDR
/

DROP INDEX PROD.FK_CO_CLM_PR_OTHR_OP_PRACT
/

DROP INDEX PROD.FK_CO_CLM_SPPL_C_RENDE_LOC
/

DROP INDEX PROD.FK_CO_CLM_SPPL_V_PREDET_TION
/

DROP INDEX PROD.FK_C_CLM_CD_Y_CALCULAT_N_TYPE
/

DROP INDEX PROD.FK_C_CLM_SPPLR_I_ED_NM_SEGM_NM
/

DROP INDEX PROD.TENANTID_CONSLTD_CLM
/
