alter session set DDL_LOCK_TIMEOUT = 300;

DROP INDEX PROD.TENANTID_UB92
/
DROP INDEX PROD.FK_U_2_UB_P_CT_OPERATIN_PRACT
/
DROP INDEX PROD.FK_UB92_UB_PRACTITIONER
/
DROP INDEX PROD.FK_UB92_UB92_DIAGNOSIS
/
DROP INDEX PROD.FK_UB92_SPPLR_INV_SEGMENTED_NM
/
