
DROP INDEX PROD.ALIAS_PAYEE_BANK_ACCOUNTS
/
DROP INDEX PROD.FK_PAYEE_ACCOUNTS_BUSIN_SEG
/
DROP INDEX PROD.FK_PAYEE_ACCOUNTS_EXTER_MBR
/
DROP INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_ACCOUNT
/
DROP INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_BROKER
/
DROP INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_MBRSHP
/
DROP INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_SPPLR
/
DROP INDEX PROD.FK_PAYEE_BANK_ACCOUNTS_SUBSCRP
/
DROP INDEX PROD.FK_PAYEE_B_ACCOUNTS_AUDIT_OG
/
DROP INDEX PROD.FK_PAYEE_B_ACCOUNTS_LIEN_LDER
/
DROP INDEX PROD.FK_PAYEE_B_ACCOUNTS_SPPLR_OC
/
DROP INDEX PROD.PAYEE_BANK_ACCOUNTS_AEDBA_1
/
DROP INDEX PROD.TENANTID_PAYEE_BANK_ACCOUNTS
/
DROP INDEX PROD.VIDDATES_PAYEE_BANK_ACCOUNTS
/