DROP INDEX PROD.TENANTID_ATTRIBUTION_LN
/
DROP INDEX PROD.FK_AT_LN_PRE_T_SRC_PAY_IBTION
/
DROP INDEX PROD.FK_ATT_N_LN_RETROACTI_RATE_LN
/
DROP INDEX PROD.FK_ATT_LN_PREM_LN_I_ON_INPUT
/
DROP INDEX PROD.FK_ATTR_ON_LN_OTHR_BIL_IPIENT
/
DROP INDEX PROD.FK_ATTR_ON_LN_CD_TRY_BILLI_AT
/
DROP INDEX PROD.FK_ATTR_N_LN_SUB_P_BILLIN_CRP
/
DROP INDEX PROD.FK_ATTR_N_LN_PREM_PAYM_R_ENTRY
/
DROP INDEX PROD.FK_ATTR_N_LN_CURRENT_B_ATE_LN
/
DROP INDEX PROD.FK_ATTR_N_LN_BNFT_PLA_SECTION
/
DROP INDEX PROD.FK_ATTR_N_LN_BILLING_C_SECTION
/
DROP INDEX PROD.FK_ATTRI_ON_LN_BI_BILL_CTION
/
DROP INDEX PROD.FK_ATTRI_ON_LN_AC_BILLI_ACCT
/
DROP INDEX PROD.FK_ATTRI_ION_LN_PREM_SU_DY_LN
/
DROP INDEX PROD.FK_ATTRI_ION_LN_PREM_RE_VABLE
/
DROP INDEX PROD.FK_ATTRI_ION_LN_BILLING_DJUST
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_SUBSCRP
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_PREM_PAYMNT
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_PREM_PAYABLE
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_PREM_BILL_LN
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_COV_TIER_SET
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_COV_TIER
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_BNFT_PLAN
/
DROP INDEX PROD.FK_ATTRIBUTION_LN_BILL_SECTION
/
DROP INDEX PROD.FK_ATTRIBUTION_LINE_PRODUCT
/
DROP INDEX PROD.FK_ATTRIBUTION_LINE_MEMBERSHIP
/
DROP INDEX PROD.FK_ATTRIBUTION_LINE_CODE_ENTRY
/
DROP INDEX PROD.FK_ATTRIBUTION_LINE_BILL
/
DROP INDEX PROD.FK_ATTRIBUTION_LINE_ACCOUNT
/
DROP INDEX PROD.ATTR_LN_PREM_REC_ISRECNCLD_IDX
/