DROP INDEX PROD.VIDDATES_MBRSHP
/
DROP INDEX PROD.TENANTID_MBRSHP
/
DROP INDEX PROD.PKDATES_MBRSHP
/
DROP INDEX PROD.MEMBER_HCC_ID
/
DROP INDEX PROD.MEMBERSHIP_CONCEPT_FULFIL_IDX
/
DROP INDEX PROD.MEMBERSHIP_AEDBA_1
/
DROP INDEX PROD.MBR_PAYEE_HCC_ID
/
DROP INDEX PROD.MBRSHP_SUBS_INDX
/
DROP INDEX PROD.FK_M_HP_POSTA_DDR_RECIPI_ADDR
/
DROP INDEX PROD.FK_M_HP_CD_TRY_EMPMNT_TUS_CD
/
DROP INDEX PROD.FK_M_HP_CD_E_RY_SALARY_ADE_CD
/
DROP INDEX PROD.FK_M_HP_CD_E_RY_HLTH_ST_S_RSN
/
DROP INDEX PROD.FK_MEMBERSHIP_SUBSCRIPTION
/
DROP INDEX PROD.FK_MEMBERSHIP_POSTAL_ADDRESS
/
DROP INDEX PROD.FK_MEMBERSHIP_PERSON_NAME
/
DROP INDEX PROD.FK_MEMBERSHIP_MEMBERSHIP
/
DROP INDEX PROD.FK_MEMBERSHIP_INDIVIDUAL
/
DROP INDEX PROD.FK_MEMBERSHIP_DIAGNOSIS
/
DROP INDEX PROD.FK_MEMBERSHIP_DEPARTMENT
/
DROP INDEX PROD.FK_MEMBERSHIP_CODE_ENTRY_UNITS
/
DROP INDEX PROD.FK_MEMBERSHIP_CODE_ENTRY
/
DROP INDEX PROD.FK_MEMBERSHIP_AUDIT_LOG
/
DROP INDEX PROD.FK_MEMBERSHIP_ATTACHMENT_SET
/
DROP INDEX PROD.FK_MB_HP_CD_E_RY_REDUCTI_RSN
/
DROP INDEX PROD.FK_MB_HP_CD_E_RY_DENIAL_SN_CD
/
DROP INDEX PROD.FK_MBR_SUB_DATES
/
DROP INDEX PROD.FK_MBRSHP_RLTP_TO_SUBSCRB_DEF
/
DROP INDEX PROD.FK_MBRSHP_MBR_DENT_INFO
/
DROP INDEX PROD.FK_MBRSHP_INDVL_INFO
/
DROP INDEX PROD.FK_MBRSHP_CD_ENTRY_VIP_RSN
/
DROP INDEX PROD.FK_MBRSHP_CD_ENTRY_INFO_SRC
/
DROP INDEX PROD.FK_MBRSHP_CD_ENTRY_EMP_TYPE
/
DROP INDEX PROD.FK_MBRSHP_CD_ENTRY_EMAIL_FRMT
/
DROP INDEX PROD.ALIAS_MBRSHP
/