set line 140 trimspool on head on echo off pagesize 999 feed off

col name for a30
col type for a5
col ts for a5

spool index_rebuilds_INDX2.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on



set echo on timing on head off


-- Took 2.5 hours in HEPYMASK

--110G
prompt (Rebuilding index: SIUDT_LST)
ALTER INDEX PROD.SIUDT_LST REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.SIUDT_LST NOPARALLEL;
prompt

--110G
prompt (Rebuilding index: ADJ_PRICE_RESULT_X_USED_O_PS)
ALTER INDEX PROD.ADJ_PRICE_RESULT_X_USED_O_PS REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.ADJ_PRICE_RESULT_X_USED_O_PS NOPARALLEL;
prompt

--105G
prompt (Rebuilding index: FK_ADDR_INFO_R_PHONE_LST_PHO)
ALTER INDEX PROD.FK_ADDR_INFO_R_PHONE_LST_PHO REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.FK_ADDR_INFO_R_PHONE_LST_PHO NOPARALLEL;
prompt

--104G
prompt (Rebuilding index: FEE_DETAIL_SVC_GEO)
ALTER INDEX PROD.FEE_DETAIL_SVC_GEO REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.FK_ADDR_INFO_R_PHONE_LST_PHO NOPARALLEL;
prompt

--102G
prompt (Rebuilding index: FK_ADDR_INFO_PHONE_LST_ADDR_O)
ALTER INDEX PROD.FK_ADDR_INFO_PHONE_LST_ADDR_O REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.FK_ADDR_INFO_PHONE_LST_ADDR_O NOPARALLEL;
prompt

--101G
prompt (Rebuilding index: FK_ADDR_INFO_POSTAL_ADDR)
ALTER INDEX PROD.FK_ADDR_INFO_POSTAL_ADDR REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.FK_ADDR_INFO_POSTAL_ADDR NOPARALLEL;
prompt

--101G
prompt (Rebuilding index: ADDR_INFO)
ALTER INDEX PROD.ADDR_INFO REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.ADDR_INFO NOPARALLEL;
prompt

--95G
prompt (Rebuilding index: SERV_COST)
ALTER INDEX PROD.SERV_COST REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.SERV_COST NOPARALLEL;
prompt

--95G
prompt (Rebuilding index: DIAG_INFO)
ALTER INDEX PROD.DIAG_INFO REBUILD PARALLEL 24 TABLESPACE INDX8;
ALTER INDEX PROD.DIAG_INFO NOPARALLEL;
prompt








set echo off timing off head on feed on


set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off

