ALTER DATABASE ADD STANDBY LOGFILE ('&1./standby_redo_01a.log') size 20M reuse;
ALTER DATABASE ADD STANDBY LOGFILE ('&1./standby_redo_02a.log') size 20M reuse;
ALTER DATABASE ADD STANDBY LOGFILE ('&1./standby_redo_03a.log') size 20M reuse;
ALTER DATABASE ADD STANDBY LOGFILE ('&1./standby_redo_04a.log') size 20M reuse;

ALTER DATABASE RECOVER MANAGED STANDBY DATABASE DISCONNECT FROM SESSION;

