SELECT 
       TRUNC(TIMESTAMP, 'HH24') HOUR
      ,A.USERNAME
      ,COUNT(*)
FROM SYS.DBA_AUDIT_TRAIL A
WHERE A.ACTION_NAME = 'LOGON'
GROUP BY A.USERNAME
        ,TRUNC(TIMESTAMP, 'HH24')
ORDER BY 1, 2
/
