OPTIONS (SKIP=1)
LOAD DATA
INFILE	'/home/oracle/eb/sqlloader/MEDICARE_TEAM/MEDICARE_TEAM_20220615.csv'
BADFILE	'/home/oracle/eb/sqlloader/MEDICARE_TEAM/MEDICARE_TEAM_20220615.bad'
DISCARDFILE '/home/oracle/eb/sqlloader/MEDICARE_TEAM/MEDICARE_TEAM_20220615.dsc'
APPEND INTO TABLE AE_CUSTOM.MEDICARE_TEAM
FIELDS TERMINATED BY '~' OPTIONALLY ENCLOSED BY '"' TRAILING NULLCOLS
(USER_ID,DEPARTMENT_NUMBER,DEPARTMENT_NAME,MANAGER,SUPERVISOR,SUPERVISOR_EMAIL_ADDRESS,USER_NAME,USER_EMAIL_ADDRESS,EFFECTIVE_DATE_FROM DATE "MM-DD-YYYY",EFFECTIVE_DATE_TO DATE "MM-DD-YYYY")


