set line 140 trimspool on head on echo off pagesize 999 feed off

col name for a30
col type for a5
col ts for a5

spool move_BLOB_TABLES.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on
set echo on timing on head off


-- BLOB_ACCOUNT 
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_ACCOUNT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_ACCOUNT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_ACCT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_ACCOUNT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295642C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_BANK_ACCOUNT 
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BANK_ACCOUNT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BANK_ACCOUNT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BANK_ACCT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_ACCOUNT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295648C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_BENEFIT_PLAN_COMPONENT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BENEFIT_PLAN_COMPONENT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BENEFIT_PLAN_COMPONENT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BNFT_PLAN_COMPONENT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BENEFIT_PLAN_COMPONENT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295657C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_ACCOUNT_BANK_ACCOUNTS
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_ACCOUNT_BANK_ACCOUNTS;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_ACCOUNT_BANK_ACCOUNTS MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_ACCT_BANK_ACCOUNTS REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_ACCOUNT_BANK_ACCOUNTS MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000446948C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_ATTRIBUTE_TYPE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_ATTRIBUTE_TYPE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_ATTRIBUTE_TYPE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_ATTRIBUTE_TYPE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_ATTRIBUTE_TYPE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295645C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_BENEFIT_NETWORK
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BENEFIT_NETWORK;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BENEFIT_NETWORK MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BNFT_NETWRK REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BENEFIT_NETWORK MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295651C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_BENEFIT_PLAN
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BENEFIT_PLAN;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BENEFIT_PLAN MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BNFT_PLAN REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BENEFIT_PLAN MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295654C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_BENEFIT_PLAN_RIDER
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BENEFIT_PLAN_RIDER;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BENEFIT_PLAN_RIDER MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BNFT_PLAN_RIDER REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BENEFIT_PLAN_RIDER MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295660C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_BENEFIT_PLAN_TEMPLATE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BENEFIT_PLAN_TEMPLATE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BENEFIT_PLAN_TEMPLATE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BNFT_PLAN_TEMPLATE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BENEFIT_PLAN_TEMPLATE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295663C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_BILL
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BILL;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BILL MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BILL REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BILL MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295666C00002$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_BILLING_RATE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BILLING_RATE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BILLING_RATE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BILLING_RATE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BILLING_RATE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295669C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_BILLING_RATE_COMPONENT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BILLING_RATE_COMPONENT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BILLING_RATE_COMPONENT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BILLING_RATE_COMPONENT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BILLING_RATE_COMPONENT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295672C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_BROKER
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BROKER;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BROKER MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BROKER REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BROKER MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295675C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_BROKER_AGENT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BROKER_AGENT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BROKER_AGENT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BROKER_AGENT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BROKER_AGENT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295678C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_BROKER_CONTRACT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_BROKER_CONTRACT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_BROKER_CONTRACT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_BROKER_CONTRCT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_BROKER_CONTRACT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295681C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_COB_POLICY
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_COB_POLICY;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_COB_POLICY MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_COB_POL REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_COB_POLICY MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295687C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_CARRIER
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_CARRIER;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_CARRIER MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_CARR REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_CARRIER MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000447009C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_CARRIER_BANK_ACCOUNTS
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_CARRIER_BANK_ACCOUNTS;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_CARRIER_BANK_ACCOUNTS MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_CARR_BANK_ACCOUNTS REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_CARRIER_BANK_ACCOUNTS MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000507141C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_CLAIM_BATCH
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_CLAIM_BATCH;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_CLAIM_BATCH MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_CLM_BATCH REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_CLAIM_BATCH MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295684C00002$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_CONSOLIDATED_CLAIM
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_CONSOLIDATED_CLAIM;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_CONSOLIDATED_CLAIM MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_CONSLTD_CLM REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_CONSOLIDATED_CLAIM MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295690C00002$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_COVERAGE_TIER_SET
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_COVERAGE_TIER_SET;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_COVERAGE_TIER_SET MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_COV_TIER_SET REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_COVERAGE_TIER_SET MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295693C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_CYCLE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_CYCLE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_CYCLE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_CYCLE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_CYCLE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295696C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_FACTOR_SET
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_FACTOR_SET;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_FACTOR_SET MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_FCT_SET REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_FACTOR_SET MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000354068C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_FEE_COMPONENT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_FEE_COMPONENT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_FEE_COMPONENT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_FEE_COMPONENT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_FEE_COMPONENT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295702C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_FUNDING_REQUEST
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_FUNDING_REQUEST;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_FUNDING_REQUEST MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_FUNDING_REQ REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_FUNDING_REQUEST MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000507237C00002$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_GROUP_POLICY
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_GROUP_POLICY;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_GROUP_POLICY MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_GRP_POL REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_GROUP_POLICY MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295705C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_HEALTH_INSURANCE_COMPANY
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_HEALTH_INSURANCE_COMPANY;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_HEALTH_INSURANCE_COMPANY MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_HLTH_INS_CO REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_HEALTH_INSURANCE_COMPANY MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295708C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_INDIVIDUAL
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_INDIVIDUAL;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_INDIVIDUAL MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_INDVL REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_INDIVIDUAL MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295711C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_LINE_OF_BUSINESS
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_LINE_OF_BUSINESS;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_LINE_OF_BUSINESS MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_LN_OF_BUSINESS REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_LINE_OF_BUSINESS MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295717C00003$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_LINE_OF_BUSINESS_GROUP
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_LINE_OF_BUSINESS_GROUP;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_LINE_OF_BUSINESS_GROUP MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_LN_OF_BUSINESS_GRP REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_LINE_OF_BUSINESS_GROUP MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295720C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_MATCH_DEFINITION
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_MATCH_DEFINITION;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_MATCH_DEFINITION MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_MATCH_DEF REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_MATCH_DEFINITION MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295723C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_MEDICARE_HICN_INFO
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_MEDICARE_HICN_INFO;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_MEDICARE_HICN_INFO MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_MEDICR_HICN_INFO REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_MEDICARE_HICN_INFO MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295726C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_MEMBER_CARE_RESERVE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_MEMBER_CARE_RESERVE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_MEMBER_CARE_RESERVE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_MBR_CARE_RESERVE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_MEMBER_CARE_RESERVE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295729C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_MEMBER_HEALTH_CONDITION
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_MEMBER_HEALTH_CONDITION;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_MEMBER_HEALTH_CONDITION MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_MBR_HLTH_COND REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_MEMBER_HEALTH_CONDITION MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295732C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_MEMBER_SELECTIONS
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_MEMBER_SELECTIONS;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_MEMBER_SELECTIONS MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_MBR_SELECTIONS REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_MEMBER_SELECTIONS MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295735C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_MEMBERSHIP
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_MEMBERSHIP;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_MEMBERSHIP MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_MBRSHP REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_MEMBERSHIP MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295738C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_NAMED_PROVIDER_GROUPING
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_NAMED_PROVIDER_GROUPING;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_NAMED_PROVIDER_GROUPING MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_NAMED_PRVDR_GROUPING REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_NAMED_PROVIDER_GROUPING MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000446983C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_OTHER_BILL_RECIPIENT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_OTHER_BILL_RECIPIENT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_OTHER_BILL_RECIPIENT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_OTHR_BILL_RECIPIENT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_OTHER_BILL_RECIPIENT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295744C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_PAYEE_BANK_ACCOUNTS
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_PAYEE_BANK_ACCOUNTS;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_PAYEE_BANK_ACCOUNTS MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_PAYEE_BANK_ACCOUNTS REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_PAYEE_BANK_ACCOUNTS MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295747C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_PAYMENT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_PAYMENT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_PAYMENT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_PAYMNT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_PAYMENT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295750C00002$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_PRACTITIONER
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_PRACTITIONER;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_PRACTITIONER MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_PRACT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_PRACTITIONER MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295753C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_PRACTITIONER_ROLE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_PRACTITIONER_ROLE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_PRACTITIONER_ROLE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_PRACT_ROLE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_PRACTITIONER_ROLE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295756C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_PREMIUM_PAYABLE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_PREMIUM_PAYABLE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_PREMIUM_PAYABLE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_PREM_PAYABLE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_PREMIUM_PAYABLE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295759C00002$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_PREMIUM_RECEIVABLE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_PREMIUM_RECEIVABLE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_PREMIUM_RECEIVABLE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_PREM_RECEIVABLE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_PREMIUM_RECEIVABLE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295762C00002$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_PRODUCT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_PRODUCT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_PRODUCT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_PROD REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_PRODUCT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295765C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_REINSURER
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_REINSURER;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_REINSURER MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_REINSURER REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_REINSURER MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295768C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_REINSURER_CONTRACT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_REINSURER_CONTRACT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_REINSURER_CONTRACT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_REINSURER_CONTRCT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_REINSURER_CONTRACT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295771C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_REPORTING_CATEGORY_SET
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_REPORTING_CATEGORY_SET;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_REPORTING_CATEGORY_SET MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_REPORTING_CAT_SET REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_REPORTING_CATEGORY_SET MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295774C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SECURITY_CONFIGURATION
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SECURITY_CONFIGURATION;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SECURITY_CONFIGURATION MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SECURITY_CONFIGURATION REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SECURITY_CONFIGURATION MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295777C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SERVICE_CATEGORY
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SERVICE_CATEGORY;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SERVICE_CATEGORY MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SERV_CAT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SERVICE_CATEGORY MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295780C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SHARED_BILLING_RATE
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SHARED_BILLING_RATE;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SHARED_BILLING_RATE MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SHARED_BILLING_RATE REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SHARED_BILLING_RATE MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295783C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SUB_COMPANY
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUB_COMPANY;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUB_COMPANY MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SUB_CO REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUB_COMPANY MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295786C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SUBSCRIPTION
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUBSCRIPTION;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUBSCRIPTION MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SUBSCRP REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUBSCRIPTION MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295789C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SUBSCRIPTION_SELECTIONS
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUBSCRIPTION_SELECTIONS;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUBSCRIPTION_SELECTIONS MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SUBSCRP_SELECTIONS REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUBSCRIPTION_SELECTIONS MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295792C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_SUBSCRIPTION_SUBSIDY
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUBSCRIPTION_SUBSIDY;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUBSCRIPTION_SUBSIDY MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SUBSCRP_SUBSIDY REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUBSCRIPTION_SUBSIDY MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295795C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SUPPLIER
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUPPLIER;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUPPLIER MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SPPLR REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUPPLIER MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295798C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_SUPPLIER_CONTRACT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUPPLIER_CONTRACT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUPPLIER_CONTRACT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SPPLR_CONTRCT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUPPLIER_CONTRACT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295801C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_SUPPLIER_LOCATION
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUPPLIER_LOCATION;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUPPLIER_LOCATION MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SPPLR_LOC REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUPPLIER_LOCATION MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295804C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_SUPPLIER_NETWORK
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_SUPPLIER_NETWORK;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_SUPPLIER_NETWORK MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_SPPLR_NETWRK REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_SUPPLIER_NETWORK MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295807C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_TAX_ENTITY
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_TAX_ENTITY;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_TAX_ENTITY MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_TAX_ENTY REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_TAX_ENTITY MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295810C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_TEST_TYPE_NON_VERSIONED
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_TEST_TYPE_NON_VERSIONED;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_TEST_TYPE_NON_VERSIONED MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_TEST_TYPE_NON_VERSIONED REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_TEST_TYPE_NON_VERSIONED MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295813C00002$$*/  (TABLESPACE DATA4);
prompt

-- BLOB_TEST_TYPE_VERSIONED
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_TEST_TYPE_VERSIONED;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_TEST_TYPE_VERSIONED MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_TEST_TYPE_VERSIONED REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_TEST_TYPE_VERSIONED MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295816C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_USER_ACCOUNT
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_USER_ACCOUNT;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_USER_ACCOUNT MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_USER_ACCT REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_USER_ACCOUNT MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295819C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_USER_DEFINED_TERM
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_USER_DEFINED_TERM;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_USER_DEFINED_TERM MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_USER_DEFINED_TERM REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_USER_DEFINED_TERM MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295822C00003$$*/  (TABLESPACE DATA4);
prompt



-- BLOB_VALUE_LIST
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_VALUE_LIST;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_VALUE_LIST MOVE TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_VAL_LST REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_VALUE_LIST MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295825C00003$$*/  (TABLESPACE DATA4);
prompt


-- BLOB_WRAP_AROUND_BENEFIT_PLAN
-- Truncate table 
prompt Truncate Table;
TRUNCATE TABLE PROD.BLOB_WRAP_AROUND_BENEFIT_PLAN;
prompt
-- Move Table to new DATA4 tbs
prompt Moving Table;
ALTER TABLE PROD.BLOB_WRAP_AROUND_BENEFIT_PLAN TABLESPACE DATA4;
prompt
--Rebuild index to INDX4 tbs
prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.BLOB_WRAP_AROUND_BNFT_PLAN REBUILD REVERSE TABLESPACE INDX4;
prompt
--Move LOB to DATA4
prompt Moving LOB 
ALTER TABLE PROD.BLOB_WRAP_AROUND_BENEFIT_PLAN MOVE LOB(SERIAL_INST_BLOB) STORE AS SECUREFILE  /*SYS_LOB0000295828C00003$$*/  (TABLESPACE DATA4);
prompt





                                   
set echo off timing off head on feed on
set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off

