spool Perf_team_grants.out

-- Performace team and DBA's

GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A229515
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A236120
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A738300
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A607483
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A605753
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A607796
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A616427
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID_AND_PHV TO A593907
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A229515
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A236120
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A738300
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A607483
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A605753
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A607796
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A616427
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SID TO A593907
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A229515
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A236120
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A738300
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A607483
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A605753
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A607796
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A616427
/
GRANT EXECUTE ON AEDBA.KILL_SESSION_BY_SQLID TO A593907
/


GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO A616427
/
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO A593907
/
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO A607796
/
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO A605753
/
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO A605753
/
GRANT EXECUTE ON SYS.DBMS_WORKLOAD_REPOSITORY TO N935883
/




spool off
