set line 140 trimspool on head on echo off pagesize 999 feed off

col name for a30
col type for a5
col ts for a5

spool redef_rebuilds_2.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on
set echo on timing on head off





ALTER INDEX PROD.PREM_SUBSIDY_LN REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.PREM_SUBSIDY_LN LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_MBRSHP REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_MBRSHP LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_SUBSCRP REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_SUBSCRP LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_IDY_LN_OTHR_BIL_PIENT REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_IDY_LN_OTHR_BIL_PIENT LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_SIDY_LN_SUBSIDY_TAILS REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SIDY_LN_SUBSIDY_TAILS LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_S_SIDY_LN_PREM_P_ABLE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_S_SIDY_LN_PREM_P_ABLE LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_P_LN_SUBS_LS_RECEIV_TAILS REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_P_LN_SUBS_LS_RECEIV_TAILS LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_PREM_SIDY_LN_PREM_RE_VABLE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SIDY_LN_PREM_RE_VABLE LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_PREM_DY_LN_PREM_ABLE_PAY_E REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_DY_LN_PREM_ABLE_PAY_E LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PRE_Y_LN_PREM_ABLE_REC_LE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PRE_Y_LN_PREM_ABLE_REC_LE LOGGING NOPARALLEL;

ALTER INDEX PROD.TENANTID_PREM_SUBSIDY_LN REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.TENANTID_PREM_SUBSIDY_LN LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_ACCT REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_ACCT LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_ACCT_ACCT REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_ACCT_ACCT LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_BNFT_PLAN REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_BNFT_PLAN LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_CD_ENTRY REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_SUBSIDY_LN_CD_ENTRY LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREMIUM_SUBSIDY_LINE_BILL REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREMIUM_SUBSIDY_LINE_BILL LOGGING NOPARALLEL;

ALTER INDEX PROD.PREM_BILL_LN REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.PREM_BILL_LN LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_SUBSCRP REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_SUBSCRP LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_MBRSHP REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_MBRSHP LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_ILL_LN_MBR_P_PRMRY_BR REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_ILL_LN_MBR_P_PRMRY_BR LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_COV_TIER REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_COV_TIER LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_COV_TIER_SET REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_COV_TIER_SET LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_COUNTY REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_COUNTY LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_ZIP REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_ZIP LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_COUNTY_COUNTY REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_COUNTY_COUNTY LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_ZIP_ZIP REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_ZIP_ZIP LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_BNFT_NETWRK REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_BNFT_NETWRK LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_CONSLTD_CLM REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_CONSLTD_CLM LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_PREM_BILL_LN_PREM_PAYABLE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_PREM_PAYABLE LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_PREM_ILL_LN_PREM_REC_VABLE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_ILL_LN_PREM_REC_VABLE LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_BILL REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_BILL LOGGING NOPARALLEL;


ALTER INDEX PROD.TENANTID_PREM_BILL_LN REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.TENANTID_PREM_BILL_LN LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_ACCOUNT REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREMIUM_BILL_LINE_ACCOUNT LOGGING NOPARALLEL;

ALTER INDEX PROD.FK_PREM_BILL_LN_ACCT_ACCT REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_ACCT_ACCT LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_PREM_BILL_LN_BNFT_PLAN REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_BNFT_PLAN LOGGING NOPARALLEL;


ALTER INDEX PROD.FK_PREM_BILL_LN_CD_ENTRY REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PREM_BILL_LN_CD_ENTRY LOGGING NOPARALLEL;


set echo off timing off head on feed on
set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off

