set line 140 trimspool on head on echo off pagesize 999 feed off

col name for a30
col type for a5
col ts for a5

spool redef_rebuilds_2.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on
set echo on timing on head off



--------------------------------------------------------------------------


prompt Moving Table;
ALTER TABLE PROD.PRACTITIONER_MEMBER MOVE TABLESPACE PROD_DATA2 NOLOGGING PARALLEL 6;
ALTER TABLE PROD.PRACTITIONER_MEMBER LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_PRACT_MBR_PRACT_ROLE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_PRACT_MBR_PRACT_ROLE LOGGING NOPARALLEL;
prompt


prompt Moving Table;
ALTER TABLE PROD.IDENTIFICATION_NUMBER MOVE TABLESPACE PROD_DATA2 NOLOGGING PARALLEL 6;
ALTER TABLE PROD.IDENTIFICATION_NUMBER LOGGING NOPARALLEL;
prompt


prompt Moving Table;
ALTER TABLE PROD.FEE_DETAIL MOVE TABLESPACE PROD_DATA2 NOLOGGING PARALLEL 6;
ALTER TABLE PROD.FEE_DETAIL LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FEE_DETAIL REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FEE_DETAIL LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FEE_DETAIL_REV_GEO REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FEE_DETAIL_REV_GEO LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FEE_DETAIL_SVC_GEO REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FEE_DETAIL_SVC_GEO LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_AUDIT_LOG REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_AUDIT_LOG LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_CODE_ENTRY REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_CODE_ENTRY LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_COUNTY REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_COUNTY LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_FEE_TABLE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_FEE_TABLE LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_MODIFIER REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_MODIFIER LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_MOD_MODIFIER2 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_MOD_MODIFIER2 LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_MOD_MODIFIER3 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_MOD_MODIFIER3 LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_MOD_MODIFIER4 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_MOD_MODIFIER4 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_PLACE_OF_SERVICE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_PLACE_OF_SERVICE LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_SERVICE REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_SERVICE LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_FEE_DETAIL_SERVICE_REV_CD REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_FEE_DETAIL_SERVICE_REV_CD LOGGING NOPARALLEL;
prompt


prompt Moving Table;
ALTER TABLE PROD.POSTAL_ADDRESS MOVE TABLESPACE PROD_DATA2 NOLOGGING PARALLEL 6;
ALTER TABLE PROD.POSTAL_ADDRESS LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.POSTAL_ADDR REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.POSTAL_ADDR LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.ADDR_TXT_UP_IDX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.ADDR_TXT_UP_IDX LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.CITY_NM_UP_IDX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.CITY_NM_UP_IDX LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_1 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_1 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_2 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_2 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_3 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.POSTAL_ADDRESS_AEDBA_3 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.POSTAL_ADDRESS_ID REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.POSTAL_ADDRESS_ID LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.POSTAL_ADDR_GEO REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.POSTAL_ADDR_GEO LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.POSTAL_INDX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.POSTAL_INDX LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.STATE_CD_UP_IDX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.STATE_CD_UP_IDX LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.ZIP_CD_UP_IDX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.ZIP_CD_UP_IDX LOGGING NOPARALLEL;
prompt


prompt Moving Table;
ALTER TABLE PROD.OPS_VALUE_REFERENCE MOVE TABLESPACE PROD_DATA2 NOLOGGING PARALLEL 6;
ALTER TABLE PROD.OPS_VALUE_REFERENCE LOGGING NOPARALLEL;
prompt

prompt Moving Table;
ALTER TABLE PROD.SUPPLIER_X_SUPPLIER_CLASS_TYPE MOVE TABLESPACE PROD_DATA2 NOLOGGING PARALLEL 6;
ALTER TABLE PROD.SUPPLIER_X_SUPPLIER_CLASS_TYPE LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX PROD.FK_SPPLR_X_ASS_TYPE_PRVDR_OMY REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX PROD.FK_SPPLR_X_ASS_TYPE_PRVDR_OMY LOGGING NOPARALLEL;
prompt







set echo off timing off head on feed on
set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off

