set line 140 trimspool on head on echo off pagesize 999 feed off

col name for a30
col type for a5
col ts for a5

spool redef_rebuilds_4.out

select name as DBNAME, to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "Start Time" from v$database;

set feed on
set echo on timing on head off



--------------------------------------------------------------------------


prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_ACCUMULATOR_DETAILS MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_ACCUMULATOR_DETAILS LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257839 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257839 LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.ACC_DTLS_AEDBA1 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.ACC_DTLS_AEDBA1 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.ACC_DTLS_INDEX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.ACC_DTLS_INDEX LOGGING NOPARALLEL;
prompt

prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_CLAIM_ACCUMULATOR MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_CLAIM_ACCUMULATOR LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257840 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257840 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.HIC_CLAIM_ACCUMULATOR_AEDBA1 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.HIC_CLAIM_ACCUMULATOR_AEDBA1 LOGGING NOPARALLEL;
prompt


prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_EVENT MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_EVENT LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257841 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257841 LOGGING NOPARALLEL;
prompt

prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_ON_DEMAND_ACKNOWLEDGMENT MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_ON_DEMAND_ACKNOWLEDGMENT LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257842 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257842 LOGGING NOPARALLEL;
prompt

prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_ON_DEMAND_REQUEST_EVENT MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_ON_DEMAND_REQUEST_EVENT LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257843 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257843 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.ONDEMAND_SEARCH_INDEX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.ONDEMAND_SEARCH_INDEX LOGGING NOPARALLEL;
prompt


prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_PUBLISHED_ACCUMULATOR MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_PUBLISHED_ACCUMULATOR LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257844 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257844 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.HIC_PUBLISHED_ACCUM_AEDBA1 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.HIC_PUBLISHED_ACCUM_AEDBA1 LOGGING NOPARALLEL;
prompt

prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_PUBLISHED_EVENT MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_PUBLISHED_EVENT LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257845 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257845 LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.HIC_PUBLISHED_EVENT_AEDBA1 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.HIC_PUBLISHED_EVENT_AEDBA1 LOGGING NOPARALLEL;
prompt


prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_SRC_TRGT_MAPPING MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_SRC_TRGT_MAPPING LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257846 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257846 LOGGING NOPARALLEL;
prompt

prompt Moving Table;
ALTER TABLE HE_CUSTOM.HIC_CVC_EVENT MOVE TABLESPACE PROD_DATA NOLOGGING PARALLEL 6;
ALTER TABLE HE_CUSTOM.HIC_CVC_EVENT LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.SYS_C00257847 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.SYS_C00257847 LOGGING NOPARALLEL;
prompt


prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.CVC_EVENT_SEARCH_INDEX REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.CVC_EVENT_SEARCH_INDEX LOGGING NOPARALLEL;
prompt

prompt Rebuilding (Index 1 of 1);
ALTER INDEX HE_CUSTOM.HIC_CVC_EVENT_AEDBA_1 REBUILD NOLOGGING PARALLEL 6 TABLESPACE PROD_INDEX;
ALTER INDEX HE_CUSTOM.HIC_CVC_EVENT_AEDBA_1 LOGGING NOPARALLEL;
prompt




set echo off timing off head on feed on
set feed off

select to_char(sysdate, 'MM-DD-YYYY HH:MI:SS AM') as "End Time" from dual;

spool off

