create or replace view PROD_DW.ACCOUNT_HISTORY_FACT as
(select "ACCOUNT_HISTORY_FACT_KEY","ACCOUNT_KEY","ACCOUNT_REPRESENTATIVE_KEY","ACCOUNT_TYPE_KEY","AUDIT_LOG_KEY","BILLED",
"CAN_HAVE_SUBSCR","ACCOUNT_CLASS_CODE_KEY","ACCOUNT_HISTORY_FACT_COUNT","DESCRIPTION"
,"ACCOUNT_EFFECTIVE_DATE_KEY","ELIGIBLE_EMPLOYEE_COUNT","EMPLOYEE_COUNT","FIRST_EFFECTIVE_DATE_KEY",
"FIRST_RENEWAL_DATE_KEY",
 "ACCOUNT_HCC_ID",
"ACCOUNT_LEVEL",
case when account_hcc_id in ('100008-01','100008','100008-02','200-00011','200-00005')  then 'XXXXX' else account_name end as "ACCOUNT_NAME",
case when account_hcc_id  in ('100008-01','100008','100008-02','200-00011','200-00005') then 'XXXXX' else PARENT_ACCOUNT_NAMES end as "PARENT_ACCOUNT_NAMES",
"INTERVAL_RENEWAL_DATE_KEY","RENEWAL_INTERVAL","ACCOUNT_STATUS","TAX_ENTITY_KEY","ACCOUNT_TERMINATION_DATE_KEY","TOP_ACCOUNT_KEY","USES_LINE_ITEM_FOR_ACCT_BLLNG","USES_LINE_ITEM_FOR_SUB_BLLNG","VERSION_EFF_DATE_KEY","VERSION_EXP_DATE_KEY","ACCOUNT_CORR_ADDRESS_KEY","BILLING_CYCLE_NAME","IS_INDIV_BROKER_RELSHIP","BUSINESS_SEG_HIST_FACT_KEY","BUSINESS_SEGMENT_KEY","TENANT_ID","IS_VIP","VIP_REASON_KEY","ATTACHMENT_SET_ID","WB_OWNER","WB_GROUP","LAST_MODIFIED_DATE_TIME","RETROACTIVE_SUBS_CHNG_PRD","RETROACTIVE_BILLING_PRD","GENERAL_CORR_SAME_AS_PARENT","OTHER_CORR_SAME_AS_PARENT" ,
case when account_hcc_id  in ('100008-01','100008','100008-02','200-00011','200-00005')  then 1 else 0 end as MASKED_IND
from PROD_DW.ALL_ACCOUNT_HISTORY_FACT where ACCOUNT_STATUS in ('a','t','p','u')  );