  CREATE OR REPLACE FORCE EDITIONABLE VIEW PROD_DW.AUTH_FACT 
  as  
  select /*+ full(AAf) */
  AUTH_FACT_KEY,ACTUAL_ADMIT_DATE_KEY,
  ACTUAL_DISCHARGE_DATE_KEY,ACTUAL_LENGTH_OF_STAY,
  ADMIT_SOURCE_KEY,ADMIT_TYPE_KEY,ADMITTING_DIAG_CODE,AUTH_ADMIT_STATUS_CODE,AUDIT_LOG_KEY,
  AVG_EXPECTED_LENGTH_OF_STAY,AUTH_FACT_COUNT,DISCHARGE_DIAG_CODE,DISCHARGE_STATUS_CODE,
  AUTHORIZED_END_DATE_KEY,AUTH_EXTERNAL_ID,FIRST_EXPECTED_ADMIT_DATE,FIRST_EXPECTED_DISCHARGE_DATE,
  AUTH_HCC_ID,IS_AGREEMENT,LAST_EXPECTED_ADMIT_DATE,LAST_EXPECTED_DISCHARGE_DATE,MAX_EXPECTED_LENGTH_OF_STAY,
  AAF.MEMBER_KEY,MIN_EXPECTED_LENGTH_OF_STAY,PRINCIPAL_DIAG_CODE,MEMBER_PRODUCT_KEY,RECEIVED_ON_DATE_KEY,
  AUTH_REFERRED_FROM_KEY,REFERRED_FROM_ADDRESS_KEY,RELEASE_OF_INFO_KEY,REQUESTED_ON_DATE_KEY,
  case when mhf.member_key is null then MEMBER_HOME_ADDRESS_KEY
  else -99 end MEMBER_HOME_ADDRESS_KEY,
  SOURCE_TYPE_CODE,AUTHORIZED_START_DATE_KEY,AUTH_STATUS_CODE,
  PLACE_OF_SERVICE_CODE,RECEIVED_ON_TIME,PATIENT_TRACKING_NUMBER,TENANT_ID,ATTACHMENT_SET_ID,
  AUTH_STATUS,WB_OWNER,WB_GROUP,LAST_MODIFIED_DATE_TIME 
  from prod_dw.ALL_AUTH_FACT AAF
  left outer join (select distinct member_key  from 
  prod_dw.all_member_history_Fact  where masked_ind = 1) mhf on  AAF.MEMBER_KEY = MHF.MEMBER_KEY
  where AUTH_STATUS in ('a','t','p','u')
;
