set echo on trimspool on

spool truncate_tbl.out

TRUNCATE TABLE PROD.TEMP_PAYABLE_PAYEE_ID;
TRUNCATE TABLE PROD.DUPLICATE_ADDRESS_SF82237;
TRUNCATE TABLE PROD.RETROACTIVE_CAP_PAYMNT_RATE_LN_MYNEXUS_BACKUP;
TRUNCATE TABLE PROD.CURRENT_CAPITAT_PAYMNT_RATE_LN_TEMP;

spool off;
