
--ALTER INDEX  PROD.FK_ATTACHMEN_TACHMENTS_ATTA_NT REBUILD ONLINE PARALLEL 6 TABLESPACE INDX3;
--ALTER INDEX  PROD.FK_ATTACHMEN_TACHMENTS_ATTA_NT NOPARALLEL;

--ALTER INDEX  PROD.FK_ATTACHME_ACHMENTS_ATTAC_SET REBUILD ONLINE PARALLEL 6 TABLESPACE INDX3;
--ALTER INDEX  PROD.FK_ATTACHME_ACHMENTS_ATTAC_SET NOPARALLEL;

--ALTER INDEX  PROD.FK_BURGESS_GRO_R_LN_RESULT_AP REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_BURGESS_GRO_R_LN_RESULT_AP NOPARALLEL;

--ALTER INDEX  PROD.FK_BURGESS_GRO_R_LN_RESULT_DR REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_BURGESS_GRO_R_LN_RESULT_DR NOPARALLEL;

--ALTER INDEX  PROD.FK_EXTERNA_SULT_X_FL_INGE_LAG REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_EXTERNA_SULT_X_FL_INGE_LAG NOPARALLEL;


--ALTER INDEX  PROD.FK_EXTE_T_X_FL_EXTERNA_RESULT REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_EXTE_T_X_FL_EXTERNA_RESULT NOPARALLEL;

--ALTER INDEX  PROD.FK_HCFA1500_ADDNL_CD_HCFA1500 REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_HCFA1500_ADDNL_CD_HCFA1500 NOPARALLEL;

--ALTER INDEX  PROD.FK_REFERRAL_CAT_TYPE_SERV_CAT REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_REFERRAL_CAT_TYPE_SERV_CAT NOPARALLEL;

--ALTER INDEX  PROD.ALIAS_SPPLR_LOC_LATEST REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.ALIAS_SPPLR_LOC_LATEST NOPARALLEL;


--ALTER INDEX  PROD.FK_SPPLR_LOC_HCCID_ENDORDT REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_SPPLR_LOC_HCCID_ENDORDT NOPARALLEL;


--ALTER INDEX  PROD.FK_SPPLR_LOC_LATEST_SPPLR REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
--ALTER INDEX  PROD.FK_SPPLR_LOC_LATEST_SPPLR NOPARALLEL;

--ALTER INDEX  PROD.PKDATES_SPPLR_LOC_LATEST REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5; 
--ALTER INDEX  PROD.PKDATES_SPPLR_LOC_LATEST NOPARALLEL;

--ALTER INDEX  PROD.SPPLR_LOC_LATEST_NAME REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5; 
--ALTER INDEX  PROD.SPPLR_LOC_LATEST_NAME NOPARALLEL;


--ALTER INDEX  PROD.SPPLR_LOC_LATEST_NPI_INDX REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5; 
--ALTER INDEX  PROD.SPPLR_LOC_LATEST_NPI_INDX NOPARALLEL;

--ALTER INDEX  PROD.VIDDATES_SPPLR_LOC_LATEST REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5; 
--ALTER INDEX  PROD.VIDDATES_SPPLR_LOC_LATEST NOPARALLEL;

--ALTER INDEX  PROD.FK_UB92_X_UB_SERV_LN_ITEM_UB92 REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5; 
--ALTER INDEX  PROD.FK_UB92_X_UB_SERV_LN_ITEM_UB92 NOPARALLEL;

--ALTER INDEX  PROD.FK_UB92_X_V_LN_ITEM_UB92_V_LN REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5; 
--ALTER INDEX  PROD.FK_UB92_X_V_LN_ITEM_UB92_V_LN NOPARALLEL;

ALTER INDEX  PROD.INS_INFO REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
ALTER INDEX  PROD.INS_INFO NOPARALLEL;

ALTER INDEX  PROD.CLM_LN_POINTER REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
ALTER INDEX  PROD.CLM_LN_POINTER NOPARALLEL;

ALTER INDEX  PROD.ABSTRACT_EOB_PAYMNT_INFO REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
ALTER INDEX  PROD.ABSTRACT_EOB_PAYMNT_INFO NOPARALLEL;

ALTER INDEX  PROD.UB92_X_UB_SERV_LN_ITEM REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
ALTER INDEX  PROD.UB92_X_UB_SERV_LN_ITEM NOPARALLEL;

ALTER INDEX  PROD.SPPLR_LOC_LATEST REBUILD ONLINE PARALLEL 6 TABLESPACE INDX5;
ALTER INDEX  PROD.SPPLR_LOC_LATEST NOPARALLEL;



