- name: Get standby count
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    set -o pipefail && {{ oracle_home }}/bin/sqlplus -s / as sysdba <<EOF
    set  echo off ver off pages 0 linesize 180 trims on head off feed off
    select count(*) from v\$DATAGUARD_CONFIG where dest_role='PHYSICAL STANDBY';
    EOF
  register: standby_count
  changed_when: "standby_count.rc == 0"
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ instance_name }}"

- name: Get standby databases
  when: standby_count.stdout | int > 0
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    set -o pipefail && {{ oracle_home }}/bin/sqlplus -s / as sysdba <<EOF
    set  echo off ver off pages 0 linesize 180 trims on head off feed off
    select db_unique_name from v\$DATAGUARD_CONFIG where dest_role='PHYSICAL STANDBY';
    EOF
  register: standby_databases
  changed_when: "standby_databases.rc == 0"
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ instance_name }}"
