- name: Backup primary archivelogs
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    $ORACLE_HOME/bin/rman target / <<EOF
    backup archivelog all;
    EOF
  environment:
    ORACLE_HOME: "{{ primary_oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
    LD_LIBRARY_PATH: "{{ primary_oracle_home }}/lib"
  delegate_to: "{{ primary_host }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"
