- name: Configure standby database delete policy
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    {{ oracle_home }}/bin/rman target / <<EOF
    CONFIGURE ARCHIVELOG DELETION POLICY TO APPLIED ON STANDBY;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
    LD_LIBRARY_PATH: "{{ oracle_home }}/lib"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Configure primary database delete policy
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    $ORACLE_HOME/bin/rman target / <<EOF
    CONFIGURE ARCHIVELOG DELETION POLICY TO SHIPPED TO ALL STANDBY BACKED UP 1 TIMES to SBT_TAPE;
    EOF
  environment:
    ORACLE_HOME: "{{ primary_oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
    LD_LIBRARY_PATH: "{{ oracle_home }}/lib"
  delegate_to: "{{ primary_host }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"
