- name: Echo srvctl add db
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    echo -e "\nAdding DB to HAS........" >> {{ log_file }}
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Check if CRS or HAS installation
  become_user: "{{ grid_user }}"
  become: true
  ansible.builtin.command: >-
    {{ grid_home }}/bin/crsctl check crs
  environment:
    ORACLE_HOME: "{{ grid_home }}"
    ORACLE_SID: "{{ asm_sid }} "
  register: crs_install
  failed_when: "crs_install.rc > 1"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Register Database with HAS
  when: crs_install.rc == 1
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.command: >-
    {{ oracle_home }}/bin/srvctl add database -db {{ db_unique_name }} -oraclehome {{ oracle_home }}
    -spfile {{ oracle_home }}/dbs/spfile{{ db_name }}.ora -instance {{ db_name }}
    -diskgroup "{{ data_dg | regex_replace('[+]') }},{{ redo1_dg | regex_replace('[+]') }},{{ redo2_dg | regex_replace('[+]') }}"
    -startoption "MOUNT"
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    LD_LIBRARY_PATH: "{{ oracle_home }}/lib"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Register Database with CRS
  when: crs_install.rc == 0
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.command: >-
    {{ oracle_home }}/bin/srvctl add database -db {{ db_unique_name }} -oraclehome {{ oracle_home }}
    -spfile {{ oracle_home }}/dbs/spfile{{ db_name }}.ora -instance {{ db_name }}
    -diskgroup "{{ data_dg | regex_replace('[+]') }},{{ redo1_dg | regex_replace('[+]') }},{{ redo2_dg | regex_replace('[+]') }}"
    -startoption "MOUNT" -dbtype single -node {{ ansible_hostname }}
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    LD_LIBRARY_PATH: "{{ oracle_home }}/lib"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Set TNSADMIN in HAS
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.command: >-
    {{ oracle_home }}/bin/srvctl setenv database -db {{ db_unique_name }} -env 'TNS_ADMIN={{ oracle_home }}/network/admin'
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    LD_LIBRARY_PATH: "{{ oracle_home }}/lib"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Stop  database
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    set -o pipefail && $ORACLE_HOME/bin/sqlplus -s / as sysdba <<EOF >> {{ log_file }}
    set  echo on ver off pages 0 linesize 180 trims on head off feed off
    shutdown immediate;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Echo srvctl config
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    echo -e "\nDB add to HAS complete." >> {{ log_file }}
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Start database with HAS
  when:
    - inventory_hostname in groups['dbservers']
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    {{ oracle_home }}/bin/srvctl start database -db {{ db_unique_name }}
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    LD_LIBRARY_PATH: "{{ oracle_home }}/lib"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"
