- name: Schedule log purge and trim OEM Job
  when: lob == "HCB"
  become_user: "{{ oracle_user }}"
  become: true
  schedule_log_file_purge:
    ORACLE_BASE: "{{ oracle_base }}"
    ORACLE_SID: "{{ db_name }}"
    SERVER_NAME: "{{ ansible_hostname }}"
    DB_UNIQUE_NAME: "{{ db_unique_name }}"
    LOGFILE: "{{ log_file }}"
    JAVA_HOME: "{{ oracle_home }}/jdk"
  register: oem_purge_job_status

- name: List oem job status
  ansible.builtin.debug:
    var: oem_purge_job_status.msg

- name: Schedule stdby archive log purgeOEM Job
  when: lob == "HCB"
  become_user: "{{ oracle_user }}"
  become: true
  schedule_stdby_archivelog_purge:
    ORACLE_BASE: "{{ oracle_base }}"
    ORACLE_SID: "{{ db_name }}"
    SERVER_NAME: "{{ ansible_hostname }}"
    DB_UNIQUE_NAME: "{{ db_unique_name }}"
    LOGFILE: "{{ log_file }}"
    JAVA_HOME: "{{ oracle_home }}/jdk"
    JOBNO: "{{ standby_database_count }}"
  register: oem_stdby_archivelog_purge_job_status

- name: List oem job status
  ansible.builtin.debug:
    var: oem_stdby_archivelog_purge_job_status.msg
