- name: Set file mgmt on primary to automatic
  when: inventory_hostname in groups['dbservers']
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    set -o pipefail && $ORACLE_HOME/bin/sqlplus -s / as sysdba <<EOF
    set  echo on
    alter system set standby_file_management = 'AUTO';
    EOF
  environment:
    ORACLE_HOME: "{{ primary_oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
  delegate_to: "{{ primary_host }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Set file mgmt on standby to automatic
  when: inventory_hostname in groups['dbservers']
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    set -o pipefail && $ORACLE_HOME/bin/sqlplus -s / as sysdba <<EOF
    set  echo on
    alter system set standby_file_management = 'AUTO';
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"
