- name: SSH  standby KeyGen command
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.command: >
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: SSH primary KeyGen command
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.command: >
    ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
    creates="~/.ssh/id_rsa"
  delegate_to: "{{ primary_host }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_create_standby_db_{{ db_name }}_successful"

- name: Fetch the standby keyfile from one server to another
  become: true
  become_user: "{{ oracle_user }}"
  ansible.builtin.fetch:
    src: "~/.ssh/id_rsa.pub"
    dest: "buffer/standby-id_rsa.pub"
    flat: true

- name: Fetch the primary keyfile from one server to another
  become: true
  become_user: "{{ oracle_user }}"
  ansible.builtin.fetch:
    src: "~/.ssh/id_rsa.pub"
    dest: "buffer/primary-id_rsa.pub"
    flat: true
  delegate_to: "{{ primary_host }}"

- name: Copy the primary key add to authorized_keys using Ansible module
  become: true
  become_user: "{{ oracle_user }}"
  ansible.posix.authorized_key:
    user: "{{ oracle_user }}"
    state: present
    key: "{{ lookup('file', 'buffer/primary-id_rsa.pub') }}"

- name: Copy the standby key add to authorized_keys using Ansible module
  become: true
  become_user: "{{ oracle_user }}"
  ansible.posix.authorized_key:
    user: "{{ oracle_user }}"
    state: present
    key: "{{ lookup('file', 'buffer/standby-id_rsa.pub') }}"
  delegate_to: "{{ primary_host }}"
