- name: Update awr
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    set -o pipefail && {{ oracle_home }}/bin/sqlplus -s / as sysdba >> $LOGFILE <<EOF
    set  echo off ver off pages 0 linesize 180 trims on head off feed off
    whenever sqlerror exit failure 1
    prompt
    prompt Enabling Block Change Tracking.......
    set linesize 160
    col STATUS format a12
    col FILENAME format a80
    ALTER DATABASE ENABLE BLOCK CHANGE TRACKING;
    SELECT status, filename FROM V\$BLOCK_CHANGE_TRACKING;
    prompt
    prompt Block Change Tracking has been enabled
    exit;
    EOF
  register: enable_bct
  changed_when: "enable_bct.rc == 0"
  environment:
    LOGFILE: "{{ log_file }}"
    SQLPATH: "{{ oracle_base }}/local/sql"
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ db_name }}"
