- name: Fetch user accounts to lock
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    {{ oracle_home }}/bin/sqlplus -s / as sysdba <<EOF > {{ stage_directory }}/{{ lst_name }}_users_to_lock.sql
    set  echo off ver off pages 0 linesize 180 trims on head off feed off
    prompt set echo on;;
    select  'alter user ' || username || ' account lock;'
    from dba_users
    where username not in (select grantee from dba_role_privs where  granted_role = 'USERS_TO_REMAIN_UNLOCKED_DURING_DEVOPS_IMPLEMENTATIONS')
    and oracle_maintained = 'N' and account_status='OPEN';
    prompt set echo off;;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ instance_name }}"
  args:
    creates: "{{ stage_directory }}/{{ lst_name }}_users_to_lock.sql"

- name: Fetch user accounts to unlock
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    {{ oracle_home }}/bin/sqlplus -s / as sysdba <<EOF > {{ stage_directory }}/{{ lst_name }}_users_to_unlock.sql
    set  echo off ver off pages 0 linesize 180 trims on head off feed off
    prompt set echo on;;
    select  'alter user ' || username || ' account unlock;'
    from dba_users
    where username not in (select grantee from dba_role_privs where  granted_role = 'USERS_TO_REMAIN_UNLOCKED_DURING_DEVOPS_IMPLEMENTATIONS')
    and oracle_maintained = 'N' and account_status='OPEN';
    prompt set echo off;;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ instance_name }}"
  args:
    creates: "{{ stage_directory }}/{{ lst_name }}_users_to_unlock.sql"

- name: Lock user accounts
  become_user: "{{ oracle_user }}"
  become: true
  ansible.builtin.shell: |
    {{ oracle_home }}/bin/sqlplus / as sysdba << EOF
    spool {{ log_file }} append
    @{{ stage_directory }}/{{ lst_name }}_users_to_lock.sql
    spool off;
    quit;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ instance_name }}"
  args:
    creates: "{{ stage_directory }}/oracle_setup_status_lock_user_accounts_{{ lst_name }}_successful"
